http_addr: ":8080"

rating:
  host: rating
  port: 8050

library:
  host: library
  port: 8060

reservation:
  host: reservation
  port: 8070

auth0:
  domain: dev-w3u5drwbbtcgp6sg.us.auth0.com
  client_id: GLcmEnDqnlRqrsugJe4iZS1bzsMabYge
  client_secret: KGEcyRPnv7tBh5kopNCgYIfl-Wj9im0zuWaUzt-E7LDTS-H4mXHDAKwXg1TCWipL
  callback_url: http://localhost:8080/oauth2/v1/auth0/callback
