name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit-test:
    name: Run go unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          cache-dependency-path: src/go.sum

      - name: Test
        run: cd v4/src && make test

  build:
    name: 'Build & Publish'
    needs: [unit-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./v4/src/docker/apiserver/Dockerfile
            image: ${{ github.repository_owner }}/library-apiserver
          - dockerfile: ./v4/src/docker/rating/Dockerfile
            image: ${{ github.repository_owner }}/library-ratingapi
          - dockerfile: ./v4/src/docker/library/Dockerfile
            image: ${{ github.repository_owner }}/library-libraryapi
          - dockerfile: ./v4/src/docker/reservation/Dockerfile
            image: ${{ github.repository_owner }}/library-reservationapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Build&Publish images"
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          tags: |
            ${{ matrix.image }}:${{ github.sha }}
            ${{ matrix.image }}:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write out the kubeconfig info
        run: |
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > /tmp/config
          chmod 0600 /tmp/config

      - name: Instal deps
        run: curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash

      - name: Lint Helm
        run: |
          helm lint ./v4/k8s/postgres-chart/
          helm lint ./v4/k8s/rsoi4-chart/

      - name: Deploy DB
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          helm upgrade storage ./v4/k8s/postgres-chart/ --install --wait --atomic --namespace=dev --values=./v4/k8s/postgres-chart/values.yaml

      - name: Deploy API
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          helm upgrade library ./v4/k8s/rsoi4-chart/ --install --wait --atomic --namespace=dev --values=./v4/k8s/rsoi4-chart/values.yaml

      - name: Cleanup kubeconfig info
        if: success() || failure()
        run: rm -f /tmp/config


  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [deploy]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update /etc/hosts
        run: sudo echo "${{ secrets.KUBE_IP }} library.example.com" | sudo tee -a /etc/hosts

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

  autograde:
    name: Autograding
    runs-on: ubuntu-latest
    needs: [integration-test]
    steps:
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
